
export const catconstants={
    GET_ALL_CATEGORY_REQUEST : 'GET_ALL_CATEGORY_REQUEST',
    GET_ALL_CATEGORY_SUCCESS : 'GET_ALL_CATEGORY_SUCCESS',
    GET_ALL_CATEGORY_FAILURE : 'GET_ALL_CATEGORY_FAILURE',
    ADD_NEW_CATEGORY_REQUEST : 'ADD_NEW_CATEGORY_REQUEST',
    ADD_NEW_CATEGORY_SUCCESS : 'ADD_NEW_CATEGORY_SUCCESS',
    ADD_NEW_CATEGORY_FAILURE : 'ADD_NEW_CATEGORY_FAILURE'
}

export const productconstants={
    GET_ALL_PRODUCT_BY_SLUG_REQUEST : 'GET_ALL_PRODUCT_BY_SLUG_REQUEST',
    GET_ALL_PRODUCT_BY_SLUG_SUCCESS : 'GET_ALL_PRODUCT_BY_SLUG_SUCCESS',
    GET_ALL_PRODUCT_BY_SLUG_FAILURE : 'GET_ALL_PRODUCT_BY_SLUG_FAILURE',
    GET_PRODUCT_PAGE_REQUEST : 'GET_PRODUCT_PAGE_REQUEST',
    GET_PRODUCT_PAGE_SUCCESS : 'GET_PRODUCT_PAGE_SUCCESS',
    GET_PRODUCT_PAGE_FAILURE : 'GET_PRODUCT_PAGE_FAILURE',
  
    GET_PRODUCT_DETAILS_BY_ID_REQUEST : 'GET_PRODUCT_DETAILS_BY_ID_REQUEST',
    GET_PRODUCT_DETAILS_BY_ID_SUCCESS : 'GET_PRODUCT_DETAILS_BY_ID_SUCCESS',
    GET_PRODUCT_DETAILS_BY_ID_FAILURE : 'GET_PRODUCT_DETAILS_BY_ID_FAILURE'

}
export const usersignupconstants = {
    USER_REGISTER_REQUEST : 'USER_REGISTER_REQUEST',
    USER_REGISTER_SUCCESS : 'USER_REGISTER_SUCCESS',
    USER_REGISTER_FAILURE : 'USER_REGISTER_FAILURE'
}

export const authconstants = {
    LOGIN_REQUEST : 'LOGIN_REQUEST',
    LOGIN_SUCCESS : 'LOGIN_SUCCESS',
    LOGIN_FAILURE : 'LOGIN_FAILURE',
    LOGOUT_REQUEST : 'LOGOUT_REQUEST',
    LOGOUT_SUCCESS : 'LOGOUT_SUCCESS',
    LOGOUT_FAILURE : 'LOGOUT_FAILURE'
}

export const cartconstants = {
    ADD_TO_CART_REQUEST:'ADD_TO_CART_REQUEST',
    ADD_TO_CART_SUCCESS:'ADD_TO_CART_SUCCESS',
    ADD_TO_CART_FAILURE:'ADD_TO_CART_FAILURE',
    RESET_CART:'RESET_CART',

    REMOVE_CART_ITEM_REQUEST: "REMOVE_CART_ITEM_REQUEST",
  REMOVE_CART_ITEM_SUCCESS: "REMOVE_CART_ITEM_SUCCESS",
  REMOVE_CART_ITEM_FAILURE: "REMOVE_CART_ITEM_FAILURE",
}
export const userconstants={
    GET_USER_ADD_REQUEST : 'GET_USER_ADD_REQUEST',
    GET_USER_ADD_SUCCESS : 'GET_USER_ADD_SUCCESS',
    GET_USER_ADD_FAILURE : 'GET_USER_ADD_FAILURE',
    ADD_USER_ADR_REQUEST : 'ADD_USER_ADR_REQUEST',
    ADD_USER_ADR_SUCCESS : 'ADD_USER_ADR_SUCCESS',
    ADD_USER_ADR_FAILURE : 'ADD_USER_ADR_FAILURE',
    ADD_USER_ORDER_REQUEST : 'ADD_USER_ORDER_REQUEST',
    ADD_USER_ORDER_SUCCESS : 'ADD_USER_ORDER_SUCCESS',
    ADD_USER_ORDER_FAILURE : 'ADD_USER_ORDER_FAILURE',
    GET_USER_ORDER_REQUEST : 'GET_USER_ORDER_REQUEST',
    GET_USER_ORDER_SUCCESS : 'GET_USER_ORDER_SUCCESS',
    GET_USER_ORDER_FAILURE : 'GET_USER_ORDER_FAILURE',
    GET_USER_ORDER_DETAILS_REQUEST :"GET_USER_ORDER_DETAILS_REQUEST ",
    GET_USER_ORDER_DETAILS_SUCCESS :"GET_USER_ORDER_DETAILS_SUCCESS ",
    GET_USER_ORDER_DETAILS_FAILURE :"GET_USER_ORDER_DETAILS_FAILURE ",

}